# Generated by Django 4.0.5 on 2022-07-21 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Liked',
        ),
    ]
