# Generated by Django 4.0.5 on 2022-07-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_blog_likes_delete_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='liked',
            field=models.ManyToManyField(to='base.profile'),
        ),
        migrations.AddField(
            model_name='blog',
            name='likes',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
