# Generated by Django 4.0.5 on 2022-07-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_blog_liked_blog_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='liked',
            field=models.ManyToManyField(blank=True, to='base.profile'),
        ),
    ]
